from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 20, 331, 511))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_add_director = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_director.setGeometry(QtCore.QRect(390, 260, 75, 23))
        self.pushButton_add_director.setObjectName("pushButton_add_director")
        self.pushButton_add_movie = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_movie.setGeometry(QtCore.QRect(670, 290, 75, 23))
        self.pushButton_add_movie.setObjectName("pushButton_add_movie")
        self.lineEdit_directorUid = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_directorUid.setGeometry(QtCore.QRect(370, 130, 113, 20))
        self.lineEdit_directorUid.setObjectName("lineEdit_directorUid")
        self.lineEdit_directorName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_directorName.setGeometry(QtCore.QRect(370, 80, 113, 20))
        self.lineEdit_directorName.setObjectName("lineEdit_directorName")
        self.lineEdit_Department = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Department.setGeometry(QtCore.QRect(370, 230, 113, 20))
        self.lineEdit_Department.setObjectName("lineEdit_Department")
        self.lineEdit_directorGender = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_directorGender.setGeometry(QtCore.QRect(370, 180, 113, 20))
        self.lineEdit_directorGender.setObjectName("lineEdit_directorGender")
        self.lineEdit_popularity = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_popularity.setGeometry(QtCore.QRect(580, 100, 113, 20))
        self.lineEdit_popularity.setObjectName("lineEdit_popularity")
        self.lineEdit_release_date = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_release_date.setGeometry(QtCore.QRect(580, 150, 113, 20))
        self.lineEdit_release_date.setObjectName("lineEdit_release_date")
        self.lineEdit_vote_average = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_vote_average.setGeometry(QtCore.QRect(580, 200, 113, 20))
        self.lineEdit_vote_average.setObjectName("lineEdit_vote_average")
        self.lineEdit_oridignal_title = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_oridignal_title.setGeometry(QtCore.QRect(580, 50, 113, 20))
        self.lineEdit_oridignal_title.setObjectName("lineEdit_oridignal_title")
        self.lineEdit_overview = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_overview.setGeometry(QtCore.QRect(580, 250, 113, 20))
        self.lineEdit_overview.setObjectName("lineEdit_overview")
        self.lineEdit_director_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_director_id.setGeometry(QtCore.QRect(720, 250, 113, 20))
        self.lineEdit_director_id.setObjectName("lineEdit_director_id")
        self.lineEdit_vote_count = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_vote_count.setGeometry(QtCore.QRect(720, 200, 113, 20))
        self.lineEdit_vote_count.setObjectName("lineEdit_vote_count")
        self.lineEdit_title = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_title.setGeometry(QtCore.QRect(720, 150, 113, 20))
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.lineEdit_revenue = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_revenue.setGeometry(QtCore.QRect(720, 100, 113, 20))
        self.lineEdit_revenue.setObjectName("lineEdit_revenue")
        self.lineEdit_movie_budget = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_movie_budget.setGeometry(QtCore.QRect(720, 50, 113, 20))
        self.lineEdit_movie_budget.setObjectName("lineEdit_movie_budget")
        self.pushButton_get_all_directors = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_get_all_directors.setGeometry(QtCore.QRect(460, 320, 75, 23))
        self.pushButton_get_all_directors.setObjectName("pushButton_get_all_directors")
        self.pushButton_get_all_movies = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_get_all_movies.setGeometry(QtCore.QRect(380, 320, 75, 23))
        self.pushButton_get_all_movies.setObjectName("pushButton_get_all_movies")
        self.pushButton_delete_movie = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete_movie.setGeometry(QtCore.QRect(750, 380, 91, 21))
        self.pushButton_delete_movie.setObjectName("pushButton_delete_movie")
        self.pushButton_delete_director = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete_director.setGeometry(QtCore.QRect(600, 380, 111, 21))
        self.pushButton_delete_director.setObjectName("pushButton_delete_director")
        self.lineEdit_director_id_for_update = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_director_id_for_update.setGeometry(QtCore.QRect(370, 470, 113, 20))
        self.lineEdit_director_id_for_update.setObjectName("lineEdit_director_id_for_update")
        self.lineEdit_new_name_for_update = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_new_name_for_update.setGeometry(QtCore.QRect(490, 470, 113, 20))
        self.lineEdit_new_name_for_update.setObjectName("lineEdit_new_name_for_update")
        self.lineEdit_director_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_director_name.setGeometry(QtCore.QRect(600, 350, 113, 20))
        self.lineEdit_director_name.setObjectName("lineEdit_director_name")
        self.lineEdit_movie_title = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_movie_title.setGeometry(QtCore.QRect(740, 350, 113, 20))
        self.lineEdit_movie_title.setObjectName("lineEdit_movie_title")
        self.lineEdit_movie_id_forupdate = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_movie_id_forupdate.setGeometry(QtCore.QRect(630, 470, 113, 20))
        self.lineEdit_movie_id_forupdate.setObjectName("lineEdit_movie_id_forupdate")
        self.lineEdit_new_title = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_new_title.setGeometry(QtCore.QRect(750, 470, 113, 20))
        self.lineEdit_new_title.setObjectName("lineEdit_new_title")
        self.pushButton_update_director_name = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_update_director_name.setGeometry(QtCore.QRect(450, 510, 75, 23))
        self.pushButton_update_director_name.setObjectName("pushButton_update_director_name")
        self.pushButton_update_movie_title = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_update_movie_title.setGeometry(QtCore.QRect(710, 510, 75, 23))
        self.pushButton_update_movie_title.setObjectName("pushButton_update_movie_title")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 300, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(580, 420, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(500, 10, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(700, 320, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(410, 30, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(690, 10, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(410, 52, 41, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(410, 110, 51, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(400, 160, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(400, 210, 61, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(580, 30, 131, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(736, 30, 61, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(600, 80, 81, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(750, 80, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(610, 130, 71, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(590, 180, 91, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(580, 230, 121, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(740, 230, 71, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(726, 130, 101, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(720, 180, 101, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(620, 330, 71, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(756, 330, 91, 20))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(390, 450, 71, 20))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(510, 450, 71, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(660, 450, 61, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(770, 450, 81, 16))
        self.label_26.setObjectName("label_26")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_add_director.setText(_translate("MainWindow", "Создать"))
        self.pushButton_add_movie.setText(_translate("MainWindow", "Создать"))
        self.pushButton_get_all_directors.setText(_translate("MainWindow", "Режисеры"))
        self.pushButton_get_all_movies.setText(_translate("MainWindow", "Фильмы"))
        self.pushButton_delete_movie.setText(_translate("MainWindow", "Удалить фильм"))
        self.pushButton_delete_director.setText(_translate("MainWindow", "Удалить режисера"))
        self.pushButton_update_director_name.setText(_translate("MainWindow", "Обновить"))
        self.pushButton_update_movie_title.setText(_translate("MainWindow", "Обновить"))
        self.label.setText(_translate("MainWindow", "Чтение"))
        self.label_2.setText(_translate("MainWindow", "Обновление"))
        self.label_3.setText(_translate("MainWindow", "Создание"))
        self.label_4.setText(_translate("MainWindow", "Удаление"))
        self.label_5.setText(_translate("MainWindow", "Режисер"))
        self.label_6.setText(_translate("MainWindow", "Фильм"))
        self.label_7.setText(_translate("MainWindow", "Имя"))
        self.label_8.setText(_translate("MainWindow", "Uid"))
        self.label_9.setText(_translate("MainWindow", "Гендер"))
        self.label_10.setText(_translate("MainWindow", "Отделение"))
        self.label_11.setText(_translate("MainWindow", "Оригинальное название"))
        self.label_12.setText(_translate("MainWindow", "Бюджет"))
        self.label_13.setText(_translate("MainWindow", "Популярность"))
        self.label_14.setText(_translate("MainWindow", "Сборы"))
        self.label_15.setText(_translate("MainWindow", "Дата показа"))
        self.label_16.setText(_translate("MainWindow", "Средняя оценка"))
        self.label_17.setText(_translate("MainWindow", "Информация о фильме"))
        self.label_18.setText(_translate("MainWindow", "ID режесера"))
        self.label_19.setText(_translate("MainWindow", "Итоговое название"))
        self.label_20.setText(_translate("MainWindow", "Количество оценок"))
        self.label_21.setText(_translate("MainWindow", "Имя режисера"))
        self.label_22.setText(_translate("MainWindow", "Название фильма"))
        self.label_23.setText(_translate("MainWindow", "ID режесера"))
        self.label_24.setText(_translate("MainWindow", "Новое имя"))
        self.label_25.setText(_translate("MainWindow", "ID фильма"))
        self.label_26.setText(_translate("MainWindow", "Новое название"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
